os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $-2
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $1
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $1
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	PCDATA	$0, $0
	0x0008 00008 (<autogenerated>:1)	PCDATA	$1, $0
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	XORPS	X0, X0
	0x0010 00016 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0015 00021 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
	0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
	rel 22+4 t=8 os.(*file).close+0
os.(*File).isdir STEXT dupok nosplit size=23 args=0x10 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).isdir(SB), DUPOK|NOSPLIT|ABIInternal, $0-16
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $-2
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·1a65e721a2ccc325b382662e7ffee780(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $1
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $1
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	PCDATA	$0, $0
	0x0008 00008 (<autogenerated>:1)	PCDATA	$1, $0
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	MOVB	$0, "".~r0+16(SP)
	0x0012 00018 (<autogenerated>:1)	JMP	os.(*file).isdir(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 c6 44 24  H.D$.H..H.D$..D$
	0x0010 10 00 e9 00 00 00 00                             .......
	rel 19+4 t=8 os.(*file).isdir+0
"".main STEXT size=202 args=0x0 locals=0x70
	0x0000 00000 (main.go:5)	TEXT	"".main(SB), ABIInternal, $112-0
	0x0000 00000 (main.go:5)	MOVQ	TLS, CX
	0x0009 00009 (main.go:5)	PCDATA	$0, $-2
	0x0009 00009 (main.go:5)	MOVQ	(CX)(TLS*2), CX
	0x0010 00016 (main.go:5)	PCDATA	$0, $-1
	0x0010 00016 (main.go:5)	CMPQ	SP, 16(CX)
	0x0014 00020 (main.go:5)	PCDATA	$0, $-2
	0x0014 00020 (main.go:5)	JLS	192
	0x001a 00026 (main.go:5)	PCDATA	$0, $-1
	0x001a 00026 (main.go:5)	SUBQ	$112, SP
	0x001e 00030 (main.go:5)	MOVQ	BP, 104(SP)
	0x0023 00035 (main.go:5)	LEAQ	104(SP), BP
	0x0028 00040 (main.go:5)	PCDATA	$0, $-2
	0x0028 00040 (main.go:5)	PCDATA	$1, $-2
	0x0028 00040 (main.go:5)	FUNCDATA	$0, gclocals·f6bd6b3389b872033d462029172c8612(SB)
	0x0028 00040 (main.go:5)	FUNCDATA	$1, gclocals·306ea4dc593c4841cf74b8270a1a332d(SB)
	0x0028 00040 (main.go:5)	FUNCDATA	$2, gclocals·f6aec3988379d2bd21c69c093370a150(SB)
	0x0028 00040 (main.go:5)	FUNCDATA	$3, "".main.stkobj(SB)
	0x0028 00040 (main.go:7)	PCDATA	$0, $0
	0x0028 00040 (main.go:7)	PCDATA	$1, $0
	0x0028 00040 (main.go:7)	MOVQ	$3, (SP)
	0x0030 00048 (main.go:7)	CALL	runtime.convT64(SB)
	0x0035 00053 (main.go:7)	PCDATA	$0, $1
	0x0035 00053 (main.go:7)	MOVQ	8(SP), AX
	0x003a 00058 (main.go:7)	PCDATA	$0, $0
	0x003a 00058 (main.go:7)	PCDATA	$1, $1
	0x003a 00058 (main.go:7)	MOVQ	AX, ""..autotmp_32+64(SP)
	0x003f 00063 (main.go:7)	MOVQ	$1, (SP)
	0x0047 00071 (main.go:7)	CALL	runtime.convT64(SB)
	0x004c 00076 (main.go:7)	PCDATA	$0, $1
	0x004c 00076 (main.go:7)	MOVQ	8(SP), AX
	0x0051 00081 (main.go:7)	PCDATA	$1, $2
	0x0051 00081 (main.go:7)	XORPS	X0, X0
	0x0054 00084 (main.go:7)	MOVUPS	X0, ""..autotmp_24+72(SP)
	0x0059 00089 (main.go:7)	MOVUPS	X0, ""..autotmp_24+88(SP)
	0x005e 00094 (main.go:7)	PCDATA	$0, $2
	0x005e 00094 (main.go:7)	LEAQ	type.int(SB), CX
	0x0065 00101 (main.go:7)	MOVQ	CX, ""..autotmp_24+72(SP)
	0x006a 00106 (main.go:7)	PCDATA	$0, $3
	0x006a 00106 (main.go:7)	PCDATA	$1, $3
	0x006a 00106 (main.go:7)	MOVQ	""..autotmp_32+64(SP), DX
	0x006f 00111 (main.go:7)	PCDATA	$0, $2
	0x006f 00111 (main.go:7)	MOVQ	DX, ""..autotmp_24+80(SP)
	0x0074 00116 (main.go:7)	PCDATA	$0, $1
	0x0074 00116 (main.go:7)	MOVQ	CX, ""..autotmp_24+88(SP)
	0x0079 00121 (main.go:7)	PCDATA	$0, $0
	0x0079 00121 (main.go:7)	MOVQ	AX, ""..autotmp_24+96(SP)
	0x007e 00126 (<unknown line number>)	NOP
	0x007e 00126 ($GOROOT\src\fmt\print.go:274)	PCDATA	$0, $1
	0x007e 00126 ($GOROOT\src\fmt\print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0085 00133 ($GOROOT\src\fmt\print.go:274)	PCDATA	$0, $2
	0x0085 00133 ($GOROOT\src\fmt\print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x008c 00140 ($GOROOT\src\fmt\print.go:274)	PCDATA	$0, $1
	0x008c 00140 ($GOROOT\src\fmt\print.go:274)	MOVQ	CX, (SP)
	0x0090 00144 ($GOROOT\src\fmt\print.go:274)	PCDATA	$0, $0
	0x0090 00144 ($GOROOT\src\fmt\print.go:274)	MOVQ	AX, 8(SP)
	0x0095 00149 ($GOROOT\src\fmt\print.go:274)	PCDATA	$0, $1
	0x0095 00149 ($GOROOT\src\fmt\print.go:274)	PCDATA	$1, $0
	0x0095 00149 ($GOROOT\src\fmt\print.go:274)	LEAQ	""..autotmp_24+72(SP), AX
	0x009a 00154 ($GOROOT\src\fmt\print.go:274)	PCDATA	$0, $0
	0x009a 00154 ($GOROOT\src\fmt\print.go:274)	MOVQ	AX, 16(SP)
	0x009f 00159 ($GOROOT\src\fmt\print.go:274)	MOVQ	$2, 24(SP)
	0x00a8 00168 ($GOROOT\src\fmt\print.go:274)	MOVQ	$2, 32(SP)
	0x00b1 00177 ($GOROOT\src\fmt\print.go:274)	CALL	fmt.Fprintln(SB)
	0x00b6 00182 (main.go:7)	MOVQ	104(SP), BP
	0x00bb 00187 (main.go:7)	ADDQ	$112, SP
	0x00bf 00191 (main.go:7)	RET
	0x00c0 00192 (main.go:7)	NOP
	0x00c0 00192 (main.go:5)	PCDATA	$1, $-1
	0x00c0 00192 (main.go:5)	PCDATA	$0, $-2
	0x00c0 00192 (main.go:5)	CALL	runtime.morestack_noctxt(SB)
	0x00c5 00197 (main.go:5)	PCDATA	$0, $-1
	0x00c5 00197 (main.go:5)	JMP	0
	0x0000 65 48 8b 0c 25 28 00 00 00 48 8b 89 00 00 00 00  eH..%(...H......
	0x0010 48 3b 61 10 0f 86 a6 00 00 00 48 83 ec 70 48 89  H;a.......H..pH.
	0x0020 6c 24 68 48 8d 6c 24 68 48 c7 04 24 03 00 00 00  l$hH.l$hH..$....
	0x0030 e8 00 00 00 00 48 8b 44 24 08 48 89 44 24 40 48  .....H.D$.H.D$@H
	0x0040 c7 04 24 01 00 00 00 e8 00 00 00 00 48 8b 44 24  ..$.........H.D$
	0x0050 08 0f 57 c0 0f 11 44 24 48 0f 11 44 24 58 48 8d  ..W...D$H..D$XH.
	0x0060 0d 00 00 00 00 48 89 4c 24 48 48 8b 54 24 40 48  .....H.L$HH.T$@H
	0x0070 89 54 24 50 48 89 4c 24 58 48 89 44 24 60 48 8b  .T$PH.L$XH.D$`H.
	0x0080 05 00 00 00 00 48 8d 0d 00 00 00 00 48 89 0c 24  .....H......H..$
	0x0090 48 89 44 24 08 48 8d 44 24 48 48 89 44 24 10 48  H.D$.H.D$HH.D$.H
	0x00a0 c7 44 24 18 02 00 00 00 48 c7 44 24 20 02 00 00  .D$.....H.D$ ...
	0x00b0 00 e8 00 00 00 00 48 8b 6c 24 68 48 83 c4 70 c3  ......H.l$hH..p.
	0x00c0 e8 00 00 00 00 e9 36 ff ff ff                    ......6...
	rel 12+4 t=17 TLS+0
	rel 49+4 t=8 runtime.convT64+0
	rel 72+4 t=8 runtime.convT64+0
	rel 97+4 t=16 type.int+0
	rel 129+4 t=16 os.Stdout+0
	rel 136+4 t=16 go.itab.*os.File,io.Writer+0
	rel 178+4 t=8 fmt.Fprintln+0
	rel 193+4 t=8 runtime.morestack_noctxt+0
type..eq.[2]interface {} STEXT dupok size=186 args=0x18 locals=0x30
	0x0000 00000 (<autogenerated>:1)	TEXT	type..eq.[2]interface {}(SB), DUPOK|ABIInternal, $48-24
	0x0000 00000 (<autogenerated>:1)	MOVQ	TLS, CX
	0x0009 00009 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0009 00009 (<autogenerated>:1)	MOVQ	(CX)(TLS*2), CX
	0x0010 00016 (<autogenerated>:1)	PCDATA	$0, $-1
	0x0010 00016 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x0014 00020 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0014 00020 (<autogenerated>:1)	JLS	176
	0x001a 00026 (<autogenerated>:1)	PCDATA	$0, $-1
	0x001a 00026 (<autogenerated>:1)	SUBQ	$48, SP
	0x001e 00030 (<autogenerated>:1)	MOVQ	BP, 40(SP)
	0x0023 00035 (<autogenerated>:1)	LEAQ	40(SP), BP
	0x0028 00040 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0028 00040 (<autogenerated>:1)	PCDATA	$1, $-2
	0x0028 00040 (<autogenerated>:1)	FUNCDATA	$0, gclocals·dc9b0298814590ca3ffc3a889546fc8b(SB)
	0x0028 00040 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0028 00040 (<autogenerated>:1)	FUNCDATA	$2, gclocals·313a5bdbfadc4f007c002a3a3588596d(SB)
	0x0028 00040 (<autogenerated>:1)	PCDATA	$0, $1
	0x0028 00040 (<autogenerated>:1)	PCDATA	$1, $0
	0x0028 00040 (<autogenerated>:1)	MOVQ	"".p+56(SP), AX
	0x002d 00045 (<autogenerated>:1)	PCDATA	$0, $2
	0x002d 00045 (<autogenerated>:1)	MOVQ	"".q+64(SP), CX
	0x0032 00050 (<autogenerated>:1)	XORL	DX, DX
	0x0034 00052 (<autogenerated>:1)	JMP	79
	0x0036 00054 (<autogenerated>:1)	PCDATA	$0, $0
	0x0036 00054 (<autogenerated>:1)	MOVQ	""..autotmp_8+32(SP), BX
	0x003b 00059 (<autogenerated>:1)	LEAQ	1(BX), DX
	0x003f 00063 (<autogenerated>:1)	PCDATA	$0, $3
	0x003f 00063 (<autogenerated>:1)	MOVQ	"".p+56(SP), BX
	0x0044 00068 (<autogenerated>:1)	PCDATA	$0, $4
	0x0044 00068 (<autogenerated>:1)	MOVQ	"".q+64(SP), SI
	0x0049 00073 (<autogenerated>:1)	PCDATA	$0, $5
	0x0049 00073 (<autogenerated>:1)	MOVQ	BX, AX
	0x004c 00076 (<autogenerated>:1)	PCDATA	$0, $2
	0x004c 00076 (<autogenerated>:1)	MOVQ	SI, CX
	0x004f 00079 (<autogenerated>:1)	CMPQ	DX, $2
	0x0053 00083 (<autogenerated>:1)	JGE	161
	0x0055 00085 (<autogenerated>:1)	MOVQ	DX, BX
	0x0058 00088 (<autogenerated>:1)	SHLQ	$4, DX
	0x005c 00092 (<autogenerated>:1)	PCDATA	$0, $6
	0x005c 00092 (<autogenerated>:1)	MOVQ	8(DX)(AX*1), SI
	0x0061 00097 (<autogenerated>:1)	PCDATA	$0, $7
	0x0061 00097 (<autogenerated>:1)	MOVQ	(DX)(AX*1), DI
	0x0065 00101 (<autogenerated>:1)	MOVQ	(DX)(CX*1), R8
	0x0069 00105 (<autogenerated>:1)	PCDATA	$0, $8
	0x0069 00105 (<autogenerated>:1)	MOVQ	8(DX)(CX*1), DX
	0x006e 00110 (<autogenerated>:1)	CMPQ	DI, R8
	0x0071 00113 (<autogenerated>:1)	JNE	146
	0x0073 00115 (<autogenerated>:1)	MOVQ	BX, ""..autotmp_8+32(SP)
	0x0078 00120 (<autogenerated>:1)	MOVQ	DI, (SP)
	0x007c 00124 (<autogenerated>:1)	PCDATA	$0, $9
	0x007c 00124 (<autogenerated>:1)	MOVQ	SI, 8(SP)
	0x0081 00129 (<autogenerated>:1)	PCDATA	$0, $0
	0x0081 00129 (<autogenerated>:1)	MOVQ	DX, 16(SP)
	0x0086 00134 (<autogenerated>:1)	CALL	runtime.efaceeq(SB)
	0x008b 00139 (<autogenerated>:1)	CMPB	24(SP), $0
	0x0090 00144 (<autogenerated>:1)	JNE	54
	0x0092 00146 (<autogenerated>:1)	PCDATA	$1, $1
	0x0092 00146 (<autogenerated>:1)	MOVB	$0, "".~r2+72(SP)
	0x0097 00151 (<autogenerated>:1)	MOVQ	40(SP), BP
	0x009c 00156 (<autogenerated>:1)	ADDQ	$48, SP
	0x00a0 00160 (<autogenerated>:1)	RET
	0x00a1 00161 (<autogenerated>:1)	MOVB	$1, "".~r2+72(SP)
	0x00a6 00166 (<autogenerated>:1)	MOVQ	40(SP), BP
	0x00ab 00171 (<autogenerated>:1)	ADDQ	$48, SP
	0x00af 00175 (<autogenerated>:1)	RET
	0x00b0 00176 (<autogenerated>:1)	NOP
	0x00b0 00176 (<autogenerated>:1)	PCDATA	$1, $-1
	0x00b0 00176 (<autogenerated>:1)	PCDATA	$0, $-2
	0x00b0 00176 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x00b5 00181 (<autogenerated>:1)	PCDATA	$0, $-1
	0x00b5 00181 (<autogenerated>:1)	JMP	0
	0x0000 65 48 8b 0c 25 28 00 00 00 48 8b 89 00 00 00 00  eH..%(...H......
	0x0010 48 3b 61 10 0f 86 96 00 00 00 48 83 ec 30 48 89  H;a.......H..0H.
	0x0020 6c 24 28 48 8d 6c 24 28 48 8b 44 24 38 48 8b 4c  l$(H.l$(H.D$8H.L
	0x0030 24 40 31 d2 eb 19 48 8b 5c 24 20 48 8d 53 01 48  $@1...H.\$ H.S.H
	0x0040 8b 5c 24 38 48 8b 74 24 40 48 89 d8 48 89 f1 48  .\$8H.t$@H..H..H
	0x0050 83 fa 02 7d 4c 48 89 d3 48 c1 e2 04 48 8b 74 02  ...}LH..H...H.t.
	0x0060 08 48 8b 3c 02 4c 8b 04 0a 48 8b 54 0a 08 4c 39  .H.<.L...H.T..L9
	0x0070 c7 75 1f 48 89 5c 24 20 48 89 3c 24 48 89 74 24  .u.H.\$ H.<$H.t$
	0x0080 08 48 89 54 24 10 e8 00 00 00 00 80 7c 24 18 00  .H.T$.......|$..
	0x0090 75 a4 c6 44 24 48 00 48 8b 6c 24 28 48 83 c4 30  u..D$H.H.l$(H..0
	0x00a0 c3 c6 44 24 48 01 48 8b 6c 24 28 48 83 c4 30 c3  ..D$H.H.l$(H..0.
	0x00b0 e8 00 00 00 00 e9 46 ff ff ff                    ......F...
	rel 12+4 t=17 TLS+0
	rel 135+4 t=8 runtime.efaceeq+0
	rel 177+4 t=8 runtime.morestack_noctxt+0
"".test STEXT nosplit size=28 args=0x20 locals=0x0
	0x0000 00000 (main.go:11)	TEXT	"".test(SB), NOSPLIT|ABIInternal, $0-32
	0x0000 00000 (main.go:11)	PCDATA	$0, $-2
	0x0000 00000 (main.go:11)	PCDATA	$1, $-2
	0x0000 00000 (main.go:11)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (main.go:11)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (main.go:11)	FUNCDATA	$2, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (main.go:12)	PCDATA	$0, $0
	0x0000 00000 (main.go:12)	PCDATA	$1, $0
	0x0000 00000 (main.go:12)	MOVQ	"".j+16(SP), AX
	0x0005 00005 (main.go:12)	MOVQ	"".i+8(SP), CX
	0x000a 00010 (main.go:12)	LEAQ	(CX)(AX*1), DX
	0x000e 00014 (main.go:14)	MOVQ	DX, "".~r2+24(SP)
	0x0013 00019 (main.go:13)	SUBQ	AX, CX
	0x0016 00022 (main.go:14)	MOVQ	CX, "".~r3+32(SP)
	0x001b 00027 (main.go:14)	RET
	0x0000 48 8b 44 24 10 48 8b 4c 24 08 48 8d 14 01 48 89  H.D$.H.L$.H...H.
	0x0010 54 24 18 48 29 c1 48 89 4c 24 20 c3              T$.H).H.L$ .
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info."".test$abstract SDWARFINFO dupok size=42
	0x0000 04 2e 74 65 73 74 00 01 01 11 69 00 00 00 00 00  ..test....i.....
	0x0010 00 11 6a 00 00 00 00 00 00 0c 61 00 0c 00 00 00  ..j.......a.....
	0x0020 00 0c 62 00 0d 00 00 00 00 00                    ..b.......
	rel 13+4 t=29 go.info.int+0
	rel 21+4 t=29 go.info.int+0
	rel 29+4 t=29 go.info.int+0
	rel 37+4 t=29 go.info.int+0
go.info.fmt.Println$abstract SDWARFINFO dupok size=42
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
	0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
	0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
	rel 0+0 t=24 type.[]interface {}+0
	rel 0+0 t=24 type.error+0
	rel 0+0 t=24 type.int+0
	rel 19+4 t=29 go.info.[]interface {}+0
	rel 27+4 t=29 go.info.int+0
	rel 37+4 t=29 go.info.error+0
go.loc.os.(*File).close SDWARFLOC dupok size=0
go.info.os.(*File).close SDWARFINFO dupok size=55
	0x0000 03 6f 73 2e 28 2a 46 69 6c 65 29 2e 63 6c 6f 73  .os.(*File).clos
	0x0010 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  e...............
	0x0020 00 00 01 9c 00 00 00 00 01 0f 7e 72 30 00 01 c4  ..........~r0...
	0x0030 01 00 00 00 00 00 00                             .......
	rel 0+0 t=24 type.*os.File+0
	rel 0+0 t=24 type.error+0
	rel 18+8 t=1 os.(*File).close+0
	rel 26+8 t=1 os.(*File).close+26
	rel 36+4 t=30 gofile..<autogenerated>+0
	rel 49+4 t=29 go.info.error+0
go.range.os.(*File).close SDWARFRANGE dupok size=0
go.debuglines.os.(*File).close SDWARFMISC dupok size=12
	0x0000 04 01 0f 06 41 06 af 04 01 03 00 01              ....A.......
go.loc.os.(*File).isdir SDWARFLOC dupok size=0
go.info.os.(*File).isdir SDWARFINFO dupok size=54
	0x0000 03 6f 73 2e 28 2a 46 69 6c 65 29 2e 69 73 64 69  .os.(*File).isdi
	0x0010 72 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  r...............
	0x0020 00 00 01 9c 00 00 00 00 01 0f 7e 72 30 00 01 63  ..........~r0..c
	0x0030 00 00 00 00 00 00                                ......
	rel 0+0 t=24 type.*os.File+0
	rel 0+0 t=24 type.bool+0
	rel 18+8 t=1 os.(*File).isdir+0
	rel 26+8 t=1 os.(*File).isdir+23
	rel 36+4 t=30 gofile..<autogenerated>+0
	rel 48+4 t=29 go.info.bool+0
go.range.os.(*File).isdir SDWARFRANGE dupok size=0
go.debuglines.os.(*File).isdir SDWARFMISC dupok size=12
	0x0000 04 01 0f 06 41 06 91 04 01 03 00 01              ....A.......
go.loc."".main SDWARFLOC size=0
go.info."".main SDWARFINFO size=66
	0x0000 03 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 07 12 00 00 00 00 00  ................
	0x0040 00 00                                            ..
	rel 0+0 t=24 type.[2]interface {}+0
	rel 0+0 t=24 type.unsafe.Pointer+0
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+202
	rel 27+4 t=30 gofile..D:\Go\src\github.com\elevenyi11\gostudy\compile\main.go+0
	rel 33+4 t=29 go.info.fmt.Println$abstract+0
	rel 37+8 t=1 "".main+126
	rel 45+8 t=1 "".main+182
	rel 53+4 t=30 gofile..D:\Go\src\github.com\elevenyi11\gostudy\compile\main.go+0
	rel 59+4 t=29 go.info.fmt.Println$abstract+15
go.range."".main SDWARFRANGE size=0
go.debuglines."".main SDWARFMISC size=35
	0x0000 04 02 13 0a 08 23 9d 06 5f 04 03 06 02 37 03 86  .....#.._....7..
	0x0010 02 fa 06 55 04 02 06 02 19 03 f9 7d fb 71 04 01  ...U.......}.q..
	0x0020 03 7c 01                                         .|.
runtime.nilinterequal·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.nilinterequal+0
runtime.memequal64·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 runtime.memequal64+0
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 08 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.nilinterequal·f+0
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
go.loc.type..eq.[2]interface {} SDWARFLOC dupok size=154
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 4f 00 00 00 00 00 00 00 5c 00 00 00 00 00 00 00  O.......\.......
	0x0020 01 00 51 00 00 00 00 00 00 00 00 00 00 00 00 00  ..Q.............
	0x0030 00 00 00 ff ff ff ff ff ff ff ff 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 ba 00 00 00 00  ................
	0x0050 00 00 00 01 00 9c 00 00 00 00 00 00 00 00 00 00  ................
	0x0060 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00 00  ................
	0x0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ba 00  ................
	0x0080 00 00 00 00 00 00 02 00 91 08 00 00 00 00 00 00  ................
	0x0090 00 00 00 00 00 00 00 00 00 00                    ..........
	rel 8+8 t=1 type..eq.[2]interface {}+0
	rel 59+8 t=1 type..eq.[2]interface {}+0
	rel 110+8 t=1 type..eq.[2]interface {}+0
go.info.type..eq.[2]interface {} SDWARFINFO dupok size=100
	0x0000 03 74 79 70 65 2e 2e 65 71 2e 5b 32 5d 69 6e 74  .type..eq.[2]int
	0x0010 65 72 66 61 63 65 20 7b 7d 00 00 00 00 00 00 00  erface {}.......
	0x0020 00 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00  ................
	0x0030 01 0b 69 00 01 00 00 00 00 00 00 00 00 10 70 00  ..i...........p.
	0x0040 00 01 00 00 00 00 00 00 00 00 10 71 00 00 01 00  ...........q....
	0x0050 00 00 00 00 00 00 00 0f 7e 72 32 00 01 01 00 00  ........~r2.....
	0x0060 00 00 00 00                                      ....
	rel 0+0 t=24 type.*[2]interface {}+0
	rel 0+0 t=24 type.bool+0
	rel 0+0 t=24 type.int+0
	rel 26+8 t=1 type..eq.[2]interface {}+0
	rel 34+8 t=1 type..eq.[2]interface {}+186
	rel 44+4 t=30 gofile..<autogenerated>+0
	rel 53+4 t=29 go.info.int+0
	rel 57+4 t=29 go.loc.type..eq.[2]interface {}+0
	rel 66+4 t=29 go.info.*[2]interface {}+0
	rel 70+4 t=29 go.loc.type..eq.[2]interface {}+51
	rel 79+4 t=29 go.info.*[2]interface {}+0
	rel 83+4 t=29 go.loc.type..eq.[2]interface {}+102
	rel 94+4 t=29 go.info.bool+0
go.range.type..eq.[2]interface {} SDWARFRANGE dupok size=0
go.debuglines.type..eq.[2]interface {} SDWARFMISC dupok size=30
	0x0000 04 01 0f 0a 08 23 06 cd 06 08 73 06 37 06 02 27  .....#....s.7..'
	0x0010 ff 06 41 06 73 06 41 06 73 04 01 03 00 01        ..A.s.A.s.....
type..eqfunc.[2]interface {} SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 type..eq.[2]interface {}+0
type..namedata.*[2]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 32 5d 69 6e 74 65 72 66 61 63 65  ...*[2]interface
	0x0010 20 7b 7d                                          {}
type.*[2]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 be 73 2d 71 08 08 08 36 00 00 00 00 00 00 00 00  .s-q...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.memequal64·f+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[2]interface {}-+0
	rel 48+8 t=1 type.[2]interface {}+0
runtime.gcbits.0a SRODATA dupok size=1
	0x0000 0a                                               .
type.[2]interface {} SRODATA dupok size=72
	0x0000 20 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00   ....... .......
	0x0010 2c 59 a4 f1 02 08 08 11 00 00 00 00 00 00 00 00  ,Y..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 02 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 type..eqfunc.[2]interface {}+0
	rel 32+8 t=1 runtime.gcbits.0a+0
	rel 40+4 t=5 type..namedata.*[2]interface {}-+0
	rel 44+4 t=6 type.*[2]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
go.loc."".test SDWARFLOC size=205
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 1c 00 00 00 00 00 00 00  ................
	0x0020 01 00 9c 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 ff ff ff ff ff ff ff ff 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 1c 00 00 00 00  ................
	0x0050 00 00 00 02 00 91 08 00 00 00 00 00 00 00 00 00  ................
	0x0060 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00  ................
	0x0070 00 00 00 00 00 00 00 0e 00 00 00 00 00 00 00 1c  ................
	0x0080 00 00 00 00 00 00 00 01 00 51 00 00 00 00 00 00  .........Q......
	0x0090 00 00 00 00 00 00 00 00 00 00 ff ff ff ff ff ff  ................
	0x00a0 ff ff 00 00 00 00 00 00 00 00 16 00 00 00 00 00  ................
	0x00b0 00 00 1c 00 00 00 00 00 00 00 01 00 52 00 00 00  ............R...
	0x00c0 00 00 00 00 00 00 00 00 00 00 00 00 00           .............
	rel 8+8 t=1 "".test+0
	rel 59+8 t=1 "".test+0
	rel 111+8 t=1 "".test+0
	rel 162+8 t=1 "".test+0
go.info."".test SDWARFINFO size=84
	0x0000 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 01 9c 13 00 00 00 00 00 00 00 00  ................
	0x0020 13 00 00 00 00 00 00 00 00 0f 7e 72 32 00 01 0b  ..........~r2...
	0x0030 00 00 00 00 00 0f 7e 72 33 00 01 0b 00 00 00 00  ......~r3.......
	0x0040 00 0e 00 00 00 00 00 00 00 00 0e 00 00 00 00 00  ................
	0x0050 00 00 00 00                                      ....
	rel 0+0 t=24 type.int+0
	rel 1+4 t=29 go.info."".test$abstract+0
	rel 5+8 t=1 "".test+0
	rel 13+8 t=1 "".test+28
	rel 24+4 t=29 go.info."".test$abstract+9
	rel 28+4 t=29 go.loc."".test+0
	rel 33+4 t=29 go.info."".test$abstract+17
	rel 37+4 t=29 go.loc."".test+51
	rel 48+4 t=29 go.info.int+0
	rel 60+4 t=29 go.info.int+0
	rel 66+4 t=29 go.info."".test$abstract+25
	rel 70+4 t=29 go.loc."".test+103
	rel 75+4 t=29 go.info."".test$abstract+33
	rel 79+4 t=29 go.loc."".test+154
go.range."".test SDWARFRANGE size=0
go.debuglines."".test SDWARFMISC size=19
	0x0000 04 02 03 06 14 06 41 06 6b 40 2e 06 41 04 01 03  ......A.k@..A...
	0x0010 73 06 01                                         s..
""..inittask SNOPTRDATA size=32
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*os.File,io.Writer+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·9fb7f0986f647f17cb53dda1484e0f7a SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 00 01                    ..........
gclocals·1a65e721a2ccc325b382662e7ffee780 SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 01 00                    ..........
gclocals·f6bd6b3389b872033d462029172c8612 SRODATA dupok size=8
	0x0000 04 00 00 00 00 00 00 00                          ........
gclocals·306ea4dc593c4841cf74b8270a1a332d SRODATA dupok size=12
	0x0000 04 00 00 00 05 00 00 00 00 01 15 14              ............
gclocals·f6aec3988379d2bd21c69c093370a150 SRODATA dupok size=12
	0x0000 04 00 00 00 03 00 00 00 00 01 03 07              ............
"".main.stkobj SRODATA size=24
	0x0000 01 00 00 00 00 00 00 00 e0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[2]interface {}+0
gclocals·dc9b0298814590ca3ffc3a889546fc8b SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 03 00                    ..........
gclocals·313a5bdbfadc4f007c002a3a3588596d SRODATA dupok size=18
	0x0000 0a 00 00 00 06 00 00 00 00 01 03 08 28 21 23 22  ............(!#"
	0x0010 24 04                                            $.
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
